### ISSUE TITLE
Feature Request Subfolder Recognition

### ISSUE THREAD

**Issue by GothLocki** [hoblin/prompt-master#23]
Hi :Thanks for the awesome app 
Currently only wildcard.txt file name  inspiration generation with its folder  in Drive letter:\stable-diffusion-webui\extensions\stable-diffusion-webui-inspiration\inspiration are showing in prompt master
Exemple Your drive letter:\stable-diffusion-webui\extensions\stable-diffusion-webui-inspiration\inspiration\nationality 

As i have Many model and embedding 
I would like to request that if possible Promot-master recognise possible folder between the wildcard.txt file name and the inspiration root folder
Exemple Your drive letter:\stable-diffusion-webui\extensions\stable-diffusion-webui-inspiration\inspiration\inspiration\AnySubfolderHere\AnySubFolder ETC...\nationality 
If it can . It would be a large boon to prompt-master 

Thanks for reading and forgice me for  any misspelling since english is not my primary language.

**Comment by hoblin** [comment]
This project is not receiving any love anymore and is about to be superseded by the online service http://promptmaster.pro 
PRs are still welcome but I'm not going to implement new features.
