### ISSUE TITLE
Refresh issue when deleting a category or a sub folder from the inspiration folder

### ISSUE THREAD

**Issue by hyppyhyppo** [hoblin/prompt-master#51]
Hello,
I have categories defined as folders in stable-diffusion-webui\extensions\stable-diffusion-webui-inspiration\inspiration.
They are all displaid in Prompt Master.
I delete a category ( the full folder) from stable-diffusion-webui\extensions\stable-diffusion-webui-inspiration\inspiration, it is still displayed in  PM.
The same happen when removing just a subset from a category folder (a sub folder containing the images).
Stopping and restarting the PM app from the docker doesn't refresh PM.

**Comment by hoblin** [comment]
Oops, I completely missed that report. It should be fixed already in the latest version.
